- name: install and start firewall
  import_tasks: install_enable.yaml
  vars:
    package: firewalld
    service: firewalld


- name: add rule
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true